### ISSUE TITLE
wss://tracker.lab.vvc.niif.hu/announce no longer working

### ISSUE THREAD

**Issue by draeder** [ngosang/trackerslist#296]
```
wss://tracker.lab.vvc.niif.hu/announce 

Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12) {
  code: 'CERT_HAS_EXPIRED'
```

**Comment by ngosang** [comment]
Removed. Thank tou!
